version: "3"

services:
  quick-mate:
    build: .
    image: flaviostutz/quick-mate
    ports:
      - 8080:8080
    # volumes:
    #   - /Users/flaviostutz/Documents/development/flaviostutz/quick-mate/server-quick-mate/static:/app/easyrtc/server-quick-mate/static
